name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo apt-get update -y
            sudo apt-get install openjdk-8-jdk
            cd ridgecrest/moqui-framework
            ./gradlew getRuntime
      
