name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo apt-get update -y
            sudo systemctl start docker
            sudo docker pull raviteja1996/ravi
            cd ridgecrest/moqui-framework/docker
            sudo docker-compose up -d moqui-ng-pg-compose.yml
            
            
            
