name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo apt-get update -y
            cd ridgecrest/moqui-framework
            sudo ./gradlew getDepends
            sudo ./gradlew build
            sudo ./gradlew cleanAll
            sudo ./gradlew getRuntime
            sudo ./gradlew addRuntime
            cd docker/simple
            sudo ./docker-build.sh ../.. raviteja1996/ravi
            cd ../
            sudo ./compose-up.sh moqui-ng-pg-compose.yml
            sudo docker ps
            
            
            
